{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vpa-creation-operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vpa-creation-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vpa-creation-operator.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
{{- end }}